### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by husthuke** [princeton-nlp/LM-BFF#1]
👍👍Your work is very enlightening and I am looking forward to the code release.

**Comment by Manas-Embold** [comment]
WHen can we expect code release

**Comment by gaotianyu1350** [comment]
Hi, thanks for your interest in our project! We are now organizing the code and document and we plan to release the code in a few days (maybe later this week).

**Comment by guotong1988** [comment]
Same question.

**Comment by gaotianyu1350** [comment]
Hi everyone! We have just released our code. Feel free to open an issue if you encounter any problems.
