### ISSUE TITLE
Specify Model Training Epochs

### ISSUE THREAD

**Issue by AlfredWGA** [princeton-nlp/LM-BFF#12]
Hi,

I want to run a fast experiment without training too many epochs. I notice that there's a argument `--num_train_epochs` in `run_experiment.sh`. I change the number from 0 to 1 or 2, but the number of epochs is always 500 (32 samples, bs=8). 

It seems like in `trainer.py` there's an argument `self.args.max_steps` specifying the training steps,

```
if self.args.max_steps > 0:
            t_total = self.args.max_steps
            num_train_epochs = self.args.max_steps // num_update_steps_per_epoch + int(
                self.args.max_steps % num_update_steps_per_epoch > 0
            )
```

But I'm not sure how to modify it. Is there any way could modify the number of epochs?

Thank you.

**Comment by gaotianyu1350** [comment]
You can delete the `--max_steps` argument in `run_experiment.sh` (line 126), and then `--num_train_epochs` should work.

**Comment by AlfredWGA** [comment]
Thank you! Very helpful.
