### ISSUE TITLE
Load and predict

### ISSUE THREAD

**Issue by sersoage** [princeton-nlp/LM-BFF#16]
Hi, thanks for the great research and codebase, and sorry for the basic question but how would you recommend to load a trained model and predict on new texts for a given task?
Thanks

**Comment by gaotianyu1350** [comment]
Hi,

For predicting on new texts, you can directly use our code (you can load a trained model by `--model_name_or_path`; there is a `--no_train` flag which allows you to only perform inference). You may need to modify the code at the end of `run.py` to save the predicted results.

**Comment by sersoage** [comment]
Thanks!
