### ISSUE TITLE
ValueError Some specified arguments are not used by the HfArgumentParser

### ISSUE THREAD

**Issue by demongolem-biz** [princeton-nlp/LM-BFF#19]
When running the run.py in the Quick Start session under Run LM-BFF, I get

`raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining args}"`

I believe it is complaining about `--evaluate_during_training`.  Is this deprecated?  Should this simply be removed, or is there a replacement?  I have had to fix the paths to Bert and Roberta in the imports so I think this just has to do with the evolution of transformers since this was originally published.

**Comment by gaotianyu1350** [comment]
Hi,

It might be due to different versions of transformers. Can you check your installed `tranformers` version? The current code is designed for `3.4.0` transformers.

**Comment by demongolem-biz** [comment]
In this case --evaluation_strategy epoch would seem to be the correct replacement.  I would agree that this would work with transformers 3.4.0.  In the quick start section, it reads "but it should work with other versions".  I think this part should be deleted and the assertion should read this requires transformers 3.4.  As it is, when I replace --evaluate_during_training, there are other errors waiting behind which also result from mismatched version.

**Comment by gaotianyu1350** [comment]
Good point, I'll edit the README.
