### ISSUE TITLE
Can this method improve data-sufficient fine-tuning?

### ISSUE THREAD

**Issue by guotong1988** [princeton-nlp/LM-BFF#3]
I am new to LM-BFF.
Thank you very much!

**Comment by gaotianyu1350** [comment]
Hi guotong, can you specify your question? What do you mean by improving "data-efficient" fine-tuning?

**Comment by guotong1988** [comment]
My fault.  I mean the data count is large enough.

**Comment by gaotianyu1350** [comment]
I see. We haven't tried fine-tuning this on the full data, but if you see Figure 3, it shows the trends for LM-BFF and fine-tuning with more training data, and they tend to converge in the end.
