### ISSUE TITLE
What is difference between --type prompt &  --type prompt-demo?

### ISSUE THREAD

**Issue by SageAgastya** [princeton-nlp/LM-BFF#31]
In the few-shot types: prompt & prompt-demo. I know that prompt-demo includes demonstrations for training and inferencing. But I have a very basic question that how the prompt-based finetuning will be trained on RoBERTa if I choose only prompt as fewshot type for training?

Is it training k-shots each at a time in the --type prompt method?
Please put some light on this query, I am getting good results but I am unaware of the way training happens.
Thanks.

**Comment by gaotianyu1350** [comment]
Hi,

If you choose prompt, it will just be prompt-based fine-tuning without demonstrations.
