### ISSUE TITLE
Table 3 uses manual label words or generated label words?

### ISSUE THREAD

**Issue by wjczf123** [princeton-nlp/LM-BFF#36]
I notice that the automatic selection of label words does not always achieve a good performance. So the results of Table 1 use manual label words?

**Comment by hujian233** [comment]
你好，我是软件学院胡剑。我已收到你的邮件，尽快给你回复。

**Comment by gaotianyu1350** [comment]
Hi,

Results in Table 3 use either manual template+manual label words (manual) or auto template+manual label words (auto).
