### ISSUE TITLE
label generation problem 

### ISSUE THREAD

**Issue by Hou-jing** [princeton-nlp/LM-BFF#39]
Hi, when I use your code to auto-generate labels, the label pairings are empty. The image is the details. And the output file is also empty. But I still have not found the wrong place.
![image](https://user-images.githubusercontent.com/75936962/173231690-6b760cce-a3cf-4834-9226-c93216e6a7d8.png)

**Comment by gaotianyu1350** [comment]
Hi,

Do you mind providing the environment you are using? Maybe it is an environment mismatch.
