### ISSUE TITLE
SNLI metrics are not supported in Transformer's glue_compute_metrics module

### ISSUE THREAD

**Issue by ramakanth-pasunuru** [princeton-nlp/LM-BFF#4]
Hi, Great work! 

I believe SNLI metrics are not supported in the glue_compute_metrics() module of Transformers library. The [line](https://github.com/princeton-nlp/LM-BFF/blob/28a89874b9ad1f3efdaec9bd6535c803f9706cf5/src/processors.py#L610) in your code tries to compute the SNLI metrics using the glue_compute_metrics(). I believe it will throw an error. Please check it once. Thanks.

**Comment by gaotianyu1350** [comment]
Hi thanks for reporting the bug! We have fixed this and you can try again now.

**Comment by ramakanth-pasunuru** [comment]
Great! thanks.
