### ISSUE TITLE
num_k parameter is not used

### ISSUE THREAD

**Issue by dyukha** [princeton-nlp/LM-BFF#40]
`run.py` accepts parameter `num_k`, which should control how many training examples per class we have. However, it's not used anywhere in the code. It seems that `num_sample` is used instead.

**Comment by hujian233** [comment]
你好，我是软件学院胡剑。我已收到你的邮件，尽快给你回复。

**Comment by gaotianyu1350** [comment]
Hi,

You are right that num_k here is a dummy arg. The number of examples is controlled by the dataset you use (for example, our provided preprocessing examples process all the datasets as k=16). Num_sample has a different meaning---it designates how many times of sampling we do for averaging in-context examples for inference.

**Comment by dyukha** [comment]
@gaotianyu1350 , thanks for the reply! Maybe it makes sense to remove `num_k`? It's also used in examples, which makes it look that the argument actually matters, which can lead to some undesired consequences for a user.

**Comment by gaotianyu1350** [comment]
Hi we decide to keep `num_k` because it is used in logging and searching for a specific run (see our explanation in README about `num_k`. But thanks for pointing it out!
