### ISSUE TITLE
Bug in tools/ensemble.py/get_labels

### ISSUE THREAD

**Issue by dyukha** [princeton-nlp/LM-BFF#41]
The function returns `label_ids`. However, when `print_name in ['sst-5', 'mr', 'cr', 'mpqa', 'subj', 'trec']`, `label_ids` is not defined. I guess there should be `return labels` in this branch?

**Comment by gaotianyu1350** [comment]
Thanks for reporting this! The bug has been fixed.

**Comment by hujian233** [comment]
你好，我是软件学院胡剑。我已收到你的邮件，尽快给你回复。
