### ISSUE TITLE
Bug in get_sbert_embedding.py?

### ISSUE THREAD

**Issue by lancorrect** [princeton-nlp/LM-BFF#44]
Hi, 

When I run get_bert_embedding.bash, I get an error bellow.

`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/roberta-large-nli-stsb-mean-tokens (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))`

Is this your code's problem or sentence-transformers' problem? Thanks a lot !

**Comment by gaotianyu1350** [comment]
It seems that you have a problem connect to Huggingface's server. Please check that the computer/server where you run this code base has internet connection to Huggingface's server.

**Comment by lancorrect** [comment]
It's so kind to receive your reply.

I checked my network environment and found that it's not stable to download models from sentence-transformers. Then I changed ip address and it works now.

Thanks again!
