### ISSUE TITLE
question about label words which consist of more than 2 sub tokens

### ISSUE THREAD

**Issue by jhwanflow** [princeton-nlp/LM-BFF#46]
Thank you for your great work.

https://github.com/princeton-nlp/LM-BFF/issues/13

I have already seen the issue above, and I understand that calculating the loss for one '[MASK]' token from multiple tokens is unavailable in normal BERT/Roberta.

But in one of your example, you used "terrible" as the negative label word, which should be tokenized into "ter" and "rible" in RobertTokenizer.

Then,  how did you map the two sub tokens "ter" and "rible"  into "[MASK]" and calculate the loss from them?

![image](https://user-images.githubusercontent.com/63226383/209763304-6e378ecb-5fea-42dc-8fda-45c41fca5eff.png)

**Comment by gaotianyu1350** [comment]
Hi,

We used `_terrible` (_ for space) instead of `terrible` (since in the example `it_was<mask>` one would want to fill in `_terrible` instead of `terrible`).
