### ISSUE TITLE
Bug in FewShotDataset module when accessing TextClassificationProcessor

### ISSUE THREAD

**Issue by ramakanth-pasunuru** [princeton-nlp/LM-BFF#5]
Hi, there is a bug in this [line](https://github.com/princeton-nlp/LM-BFF/blob/28a89874b9ad1f3efdaec9bd6535c803f9706cf5/src/dataset.py#L265). For the text classification datasets (mr, sst-5, subj, trec, cr, mpqa), the processor module requires the task name as input. Right now the above line throws error.

**Comment by gaotianyu1350** [comment]
Hi thanks for the report. I remember that it has been fixed in a previous commit and I didn't encounter the problem using the latest one. Can you pull the latest commit and try again?

**Comment by gaotianyu1350** [comment]
Oh sorry for that... It seems that I forgot to push the commit. It should work now.

**Comment by ramakanth-pasunuru** [comment]
Thanks.
