### ISSUE TITLE
About the SNLI datasets

### ISSUE THREAD

**Issue by MatthewCYM** [princeton-nlp/LM-BFF#8]
Hi Tianyu,

Thanks for your code.  I found that the downloaded SNLI dataset is slightly different from the original one. The statistics are shown below:
yours:
9843 dev.tsv
9825 test.tsv
549368 train.tsv
569036 total

original:
10001 snli_1.0_dev.txt
10001 snli_1.0_test.txt
550153 snli_1.0_train.txt
570246 total

May I ask what changes have you made?

Regards,
Yiming

**Comment by gaotianyu1350** [comment]
Hi Yiming, 

It's because SNLI contains some instances with no label (the field of "gold label" is "-" because the annotators did not reach an agreement). We just filtered them out. Sorry that we didn't mention this in the paper & README, and we will update with the details later.
